version: "3.8"
services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: password
        volumes:
            - mongo_data:/data/db
        restart: unless-stopped

    postgres:
        image: postgres:latest
        container_name: my-postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: mysecretpassword
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        restart: unless-stopped

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - "80:80"
        restart: unless-stopped

volumes:
    mongo_data:
        driver: local
    postgres_data:
        driver: local
